### ISSUE TITLE
Error: length of response must be the same as predictors

### ISSUE THREAD

**Issue by ghost** [hcji/KPIC2#2]
I have tried using KPIC2 and it works for almost everything except for the two problems highlighted below. The first problem has to do with group alignment, even though it works, the following error and warning is given.
> groups_align <- PICset.align(groups_raw, method='fftcc',move='loess')
Warning messages:
1: In peakinfoj[, c("rt", "rtmin", "rtmax")] + lag_rt :
  longer object length is not a multiple of shorter object length
2: In peakinfoj[, c("rt", "rtmin", "rtmax")] + lag_rt :
  longer object length is not a multiple of shorter object length
3: In peakinfoj[, c("rt", "rtmin", "rtmax")] + lag_rt :
  longer object length is not a multiple of shorter object length

Lastly, plotting Random Forest using the ShinyApp produces the error in the main heading. Even if I change the parameters on the number of trees to grow, number of nodes e.t.c , the problem persists. Changing the length of the response and predictors cannot be simply solved by changing parameters and is a problem that lies with how the app is handling data.
Attached is a picture that shows the error problem.
![randomforesterror](https://user-images.githubusercontent.com/29667095/30695203-94fa638a-9ed7-11e7-95f1-f6b2c43d56d9.PNG)

**Comment by hcji** [comment]
First, the warning happens because of a matrix plus a vector. This has been fixed, but the original result is no problem. You can try 
`matrix(1:9, 3, 3) + c(1,2,3)`
The result is the same as
`matrix(1:9, 3, 3) + matrix(1:3, 3, 3)`

Second, the error comes from your length of `label` not equals to your number of samples. The `label` means the classes of each sample belongs to.

**Comment by ghost** [comment]
So how can I correct the second error ? I have tried changing labels in this line of code with 1, 2 or 3 to  to match my number of samples and its still not working.
labels<- c(rep(1,9), rep(2,9)) # class labels
analyst.RF(labels, data$data.mat)

**Comment by hcji** [comment]
The example code 
` labels<- c(rep(1,9), rep(2,9))` 
means the first 9 samples belong to class 1, and the last 9 samples belong to class 2.
you can also replace with a character.

**Comment by ghost** [comment]
Fixed. Everything now works fine. I was wondering if you could also supply the code that allows one to plot models,  dendograms, trees, Draftman's displays, error rate of random forest  or other plots that exhibit the differences between the two classes. The initial version of KPIC2 that I used a month ago allowed one to plot multiple other plots and was wondering if its still possible to plot them with the new version.

**Comment by hcji** [comment]
thanks for your suggestion, I will add these functions to the new version in a few days. for now, may be you can rely the ropls or randomForest package, directly.

**Comment by ghost** [comment]
Has a new version with more plotting capabilities been made ? Just asking out of curiosity.

**Comment by hcji** [comment]
You can plot the error rate and trees in the shiny app, now

**Comment by ghost** [comment]
Thank you so much for the help. I will close the issue.

**Comment by ghost** [comment]
Do I need to download a new coat of KPCI2 of I can use the old one, because currently as things stand, I can only plot the error rate but cannot plot decision trees. When I try using  other packages to plot the data from KPCI2 (e.g party, randomForest), they are not compatible with the way your data is presented.
![kpci2shinyappy](https://user-images.githubusercontent.com/29667095/31540691-98cd423e-b00c-11e7-8cef-6c0c4f865c91.PNG)

**Comment by hcji** [comment]
please reinstall
